Chart.yamlname: observableagent
type: application
version: 0.1.3
apiVersion: v2
description: A Helm chart for Observable Stack agent
dependencies:
- name: kube2iam
  condition: kube2iam.enabled
  version: "0.21.6"
  repository: "https://fluent.github.io/helm-charts"
- name: deepflow-agent
  condition: deepflow-agent.enabled
  version: "6.1.8"
  repository: "https://deepflowys.github.io/deepflow"
- name: grafana-agent-operator
  condition: grafana-agent.enabled
  version: "0.2.8"
  repository: "https://grafana.github.io/helm-charts"
- name: fluent-bit
  condition: fluent-bit.enabled
  version: "0.21.6"
  repository: "https://fluent.github.io/helm-charts"
- name: prometheus
  condition: prometheus.enabled
  version: "19.0.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: kube-state-metrics
  condition: kube-state-metrics.enabled
  version: "4.24.0"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: prometheus-node-exporter
  condition: prometheus-node-exporter.enabled
  version: "3.1.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: prometheus-to-cloudwatch
  condition: prometheus-to-cloudwatch.enabled
  version: "0.1.3"
  repository: "https://artifact.onwalk.net/chartrepo/k8s/"
